import type { AppRouterInstance } from "next/dist/shared/lib/app-router-context.shared-runtime";
import type { ChangeEvent, Dispatch, MutableRefObject, Ref, RefObject, SetStateAction } from "react";
import type { AuthorIpItem } from "../../lib/authorIp";
import type { NotesAskDialogueStyleMode } from "../../lib/notesAskDialogueStyle";
import type { NotesAskSource, NotesAskWebSource } from "../../lib/notesAskCitation";
import type { NotebookCardVisual } from "../../lib/notebookCardThemes";
import type { WorkItem } from "../../lib/worksTypes";

export type SharedBrowseContext = {
  ownerUserId: string;
  access: "read_only" | "edit";
};

export type WorkbenchMobilePanel = "chat" | "sources";

export type NotesWorkbenchNoteItem = {
  noteId: string;
  title?: string;
  notebook?: string;
  ext?: string;
  inputType?: string;
  sourceHint?: string;
  parseState?: string;
  citeState?: string;
  retrieveState?: string;
  ragIndexError?: string;
};

export type NotesAskWorkbenchTurn = {
  id: string;
  role: "user" | "assistant";
  content: string;
  streaming?: boolean;
  streamingPhase?: string;
  streamingReasoning?: string;
  supplementContent?: string;
  lowConfidence?: boolean;
  sources?: NotesAskSource[];
  webSources?: NotesAskWebSource[];
  followUpQuestions?: string[];
  hintSuggestions?: string[];
};

export type NotesWorkbenchCreationProgress = {
  text: string;
  busy: boolean;
  doneTone: boolean;
  warnTone: boolean;
  billingPodcast: boolean;
  billingDraft: boolean;
};

export type NotesWorkbenchContextValue = {
  router: AppRouterInstance;
  userPrefersNotebookHubRef: MutableRefObject<boolean>;
  selectedNotebook: string;
  notebooks: string[];
  notebookVisualByName: Record<string, NotebookCardVisual>;
  sharedBrowse: SharedBrowseContext | null;
  dismissNotesBlockingOverlays: () => void;
  setSelectedNotebook: Dispatch<SetStateAction<string>>;
  setSharedBrowse: Dispatch<SetStateAction<SharedBrowseContext | null>>;
  openNotebook: (nb: string) => void;
  setNotebookModalError: Dispatch<SetStateAction<string>>;
  setNewNotebookName: Dispatch<SetStateAction<string>>;
  setShowNotebookModal: Dispatch<SetStateAction<boolean>>;
  workbenchMobilePanel: WorkbenchMobilePanel;
  setWorkbenchMobilePanel: Dispatch<SetStateAction<WorkbenchMobilePanel>>;
  draftSelectedNoteIds: string[];
  sourcesPanelCollapsed: boolean;
  setSourcesPanelCollapsed: Dispatch<SetStateAction<boolean>>;
  styleNoteMetas: Array<{
    noteId: string;
    updatedAt: string;
    noteRagBodyHash: string;
    contentVersion: string;
    ragChunkCount: number;
    styleFeaturesReady: boolean;
    bodyLength: number;
  }>;
  setNotebookStyleItem: Dispatch<SetStateAction<AuthorIpItem | null>>;
  setStyleActionToast: Dispatch<SetStateAction<string>>;
  setError: Dispatch<SetStateAction<string>>;
  notebookStyleItem: AuthorIpItem | null;
  setShowAddNoteModal: Dispatch<SetStateAction<boolean>>;
  setImportUrlError: Dispatch<SetStateAction<string>>;
  styleActionToast: string;
  stats: { total: number };
  hasMoreNotes: boolean;
  notesSorted: NotesWorkbenchNoteItem[];
  selectAllOnPageInputRef: Ref<HTMLInputElement>;
  allNotesOnPageSelected: boolean;
  onSelectAllOnPageChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  loading: boolean;
  isSourceUsable: (n: NotesWorkbenchNoteItem) => boolean;
  openPreview: (noteId: string, opts?: { ext?: string; inputType?: string }) => void | Promise<void>;
  noteExtLabel: (ext?: string) => string;
  freshNoteIds: string[];
  isNoteInStyleSnapshot: (noteId: string, styleItem: AuthorIpItem | null) => boolean;
  noteMenuOpenId: string | null;
  setNoteMenuOpenId: Dispatch<SetStateAction<string | null>>;
  setRenameNoteId: Dispatch<SetStateAction<string | null>>;
  setRenameNoteTitle: Dispatch<SetStateAction<string>>;
  confirmDeleteNote: (noteId: string) => void | Promise<void>;
  toggleDraftNote: (noteId: string) => void;
  renameNoteId: string | null;
  renameNoteTitle: string;
  saveRenameNote: (noteId: string) => void | Promise<void>;
  renameDebugLog: string;
  notePage: number;
  setNotePage: Dispatch<SetStateAction<number>>;
  notesAskMenuOpen: boolean;
  setNotesAskMenuOpen: Dispatch<SetStateAction<boolean>>;
  podcastGenBusy: boolean;
  openPodcastFlow: () => void;
  openArticleFlow: () => void;
  notesAskMessages: NotesAskWorkbenchTurn[];
  clearNotesAskConversation: () => void;
  notesAskError: string;
  setNotesAskError: Dispatch<SetStateAction<string>>;
  notesAskScrollRef: Ref<HTMLDivElement>;
  notesAskLastUserMessageId: string | null;
  copyNotesAskAnswer: (text: string) => void | Promise<void>;
  beginEditNotesAskUserTurn: (id: string, content: string) => void;
  openPreviewFromAskSource: (source: NotesAskSource) => void | Promise<void>;
  setNotesAskQuestion: Dispatch<SetStateAction<string>>;
  notesAskTextareaRef: RefObject<HTMLTextAreaElement | null>;
  notesAskNoteBusyId: string | null;
  saveAskAnswerAsNote: (content: string, messageId: string) => void | Promise<void>;
  notebookDigestSummary: string;
  notesAskQuestion: string;
  notesAskBusy: boolean;
  submitNotesAsk: () => void | Promise<void>;
  notesAskDialogueStyle: NotesAskDialogueStyleMode;
  setNotesAskDialogueStyle: Dispatch<SetStateAction<NotesAskDialogueStyleMode>>;
  notebookStylePrompt: string;
  scrollToNotebookStyleLearn: () => void;
  notesAskStreamAbortRef: MutableRefObject<AbortController | null>;
  notesAskDebugClient: boolean;
  notesAskDebugPack: {
    streamReady: boolean;
    streamJsonPretty: string;
  };
  notesAskDebugCurls: {
    streamCurl: string;
    streamUrl: string;
  };
  notesAskDebugCopied: string;
  copyNotesAskDebug: (text: string, kind: "stream" | "curlStream") => void | Promise<void>;
  notesWorkbenchCreationProgress: NotesWorkbenchCreationProgress | null;
  worksPanelExpanded: boolean;
  setWorksPanelExpanded: Dispatch<SetStateAction<boolean>>;
  notesWorksViewAllHref: string;
  podcastWorks: WorkItem[];
  podcastWorksLoading: boolean;
  podcastWorksError: string;
  setPodcastWorksError: Dispatch<SetStateAction<string>>;
  fetchPodcastWorks: () => void | Promise<void>;
  notesPendingStudioWork: WorkItem | null;
  notesPendingStudioSubtitle: string;
};
